// vim: set syntax=asciidoc:

// Start of document parameters

:icons: font
:sectnums:
:toc: left

// End of document parameters


.TODO
- Add a row to each table describing the relevancy of the book in relation to OpenIndiana Hipster.
* See the SmartOS wiki for an example of this where they compare various OSOL commercial books to illumos.




= OpenSolaris Redistributable Docs - 2009.07.15

Consisting of 41 titles and originally published on July 15th, 2009, this collection of books compose the final docs release of the OpenSolaris project.
For ease of use, the titles have been organized by subject matter and grouped according to their intended target audience.
For each title, a brief synopsis has been provided.
Otherwise, the books are exactly as originally published.
No editing of any kind has been performed on any of the titles.
This documentation collection has been released under the https://www.openoffice.org/licenses/PDL.html[Public Documentation License (PDL)].


[NOTE]
====
When using these books, please bear in mind:

- The OpenIndiana Project has republished these books primarily for their reference value.
- Although vast portions of these books are still revelant, significant divergence has occured between OpenIndiana Hipster and OpenSolaris/Solaris Express.
- Some of the books in this collection reference publications which were either never opensourced by Sun Microsystems or never released by the OpenSolaris Project.
  For example, the _OpenSolaris Developer's Reference Guide_ was never released as part of this collection.
- There are lots of broken links to OpenSolaris.org and Sun Microsystems.
- In some cases, it may be possible to follow broken links by using the https://archive.org/web/[Internet Archive Wayback Machine].
====

.Titles Updated by the illumos Project
Several of the development related titles were updated in the early days of the illumos project.
The illumos updated titles can be found here: https://illumos.org/books/

.The OpenIndiana Project's Documentation Update Effort
An effort currently exists within the OpenIndiana community to review the 2009.07.15 docs collection for updating.
If you wish to participate in this effort, please indicate your interest in one or more of the following ways:


|===
| Resource | URL

| User Support IRC channel
| irc://irc.freenode.net/openindiana[#openindiana on irc.freenode.net]

| Development IRC channel
| irc://irc.freenode.net/oi-dev[#oi-dev on irc.freenode.net]

| Documentation IRC channel
| irc://irc.freenode.net/oi-documentation[#oi-documentation on irc.freenode.net]

| OpenIndiana Mailing Lists
| http://openindiana.org/mailman
|===


== Basic Systems Administration


=== Getting Started with OpenSolaris

[cols="1,4"]
|===

| Document Link
| link:./20090715/getstart/html/solarisinstall.html[Getting Started With OpenSolaris]

| Topics
| The guide provides an introduction to the OpenSolaris™ operating system, as well as instructions for installing the current OpenSolaris release on your system.
This guide is intended to help you install and set up the free binary distribution of the OpenSolaris software and make your initial experience with it a successful one.

| Relevancy to OpenIndiana Hipster
| < placeholder for content>

| Target Audience
| This book is intended for anyone interested in installing and exploring the OpenSolaris operating system.

| Requirements
| Experience using the Solaris Operating System (OS) or another UNIX® version is recommended.
|===


=== System Administration Guide: Basic Administration

[cols="1,4"]
|===

| Document Link 
| link:./20090715/SYSADV1/html/sysadv1.html[System Administration Guide: Basic Administration]

| Topics
a| - User accounts and groups +
- Server and client support +
- Shutting down and booting a system +
- Managing services +
- Managing software (packages and patches)

| Relevancy to OpenIndiana Hipster
| < placeholder for content>

| Target Audience
| This book is intended for anyone responsible for administering one or more systems running the Solaris release.

| Requirements
| This book assumes you have installed the Solaris Express Operating System and set up all the networking software that you plan to use.
To use this book, you should have 1-2 years of UNIX® system administration experience.
Attending UNIX system administration training courses might be helpful.
|===

== Intermediate & Advanced Systems Administration


=== OpenSolaris Managing Boot Environments

[cols="1,4"]
|===

| Document Link
| link:./20090715/snapupgrade/html/solarisinstall.html[OpenSolaris Managing Boot Environments]

| Topics
| A boot environment is a bootable instance of an OpenSolaris™ operating system image plus any other application software packages installed into that image.
System administrators can maintain multiple boot environments on their systems, and each boot environment can have different software versions installed.

Upon the initial installation of OpenSolaris onto a system, a boot environment is created.
Use the beadm(1M) utility or the Package Manager to administer additional boot environments on your system.

| Relevancy to OpenIndiana Hipster
| < placeholder for content>

| Target Audience
| This book is intended for anyone responsible for administering one or more systems running the OpenSolaris operating system.

| Requirements
| Experience using the Solaris Operating System (OS) or another UNIX® version is recommended.
|===


=== OpenSolaris 2009.06 Image Packaging System Guide

[cols="1,4"]
|===

| Document Link
| link:./20090715/IMGPACKAGESYS/html/ips.html[OpenSolaris 2009.06 Image Packaging System Guide]

| Topics
a| The Image Packaging System, pkg(5), is a framework that provides for software lifecycle management such as installation, upgrade, and removal of packages.
IPS also provides users the ability to create their own software packages, create and manage packaging repositories, and mirror existing packaging repositories.

With IPS, users can perform the following tasks:

- Create and manage images

- Install new packages and update existing packages

- Manage and search the software on your system

With the IPS publication tools, developers can perform the following:

- Create and manage packaging repositories

- Create and publish packages to a packaging repository

- Provide a content mirror for an existing packaging repository

- Retrieve the contents of an existing package from a packaging repository

- Republish the contents of an existing package to a packaging repository

| Relevancy to OpenIndiana Hipster
| < placeholder for content>

| Target Audience
| This book is intended for system administrators, end users, and developers.

| Requirements
| Experience using the Solaris Operating System (OS) or another UNIX® version is recommended.
|===


=== Solaris CIFS Administration Guide

[cols="1,4"]
|===

| Document Link
| link:./20090715/SSMBAG/html/ssmbag.html[Solaris CIFS Administration Guide]

| Topics
a| - Solaris CIFS service, which enables you to configure a Solaris system to make CIFS shares available to CIFS clients.
- Native identity mapping services, which enables you to map user and group identities between Solaris systems and Windows systems.

| Relevancy to OpenIndiana Hipster
| < placeholder for content>

| Target Audience
| This book is intended for system administrators and end users.
Both Solaris and Windows system administrators can use this information to configure and integrate the Solaris CIFS service into a Windows environment.

In addition, system administrators can configure the identity mapping service.
Finally, the chapter about the Solaris CIFS client is primarily intended for Solaris users who would like to mount CIFS shares.
The Solaris CIFS client chapter also includes tasks to be performed by a system administrator.

| Requirements
| Experience using the Solaris Operating System (OS) or another UNIX® version is recommended.
|===

=== Solaris ZFS Administration Guide

[cols="1,4"]
|===

| Document Link
| link:./20090715/ZFSADMIN/html/zfsadmin.html[Solaris ZFS Administration Guide]

| Topics
a| - ZFS storage pool and file system creation and management
- Snapshots
- Clones
- Backups
- Using access control lists (ACLs) to protect ZFS files
- Using ZFS on a Solaris system with zones installed
- Emulated volumes
- Troubleshooting
- Data recovery

| Relevancy to OpenIndiana Hipster
| < placeholder for content>

| Target Audience
| This guide is intended for anyone who is interested in setting up and managing Solaris ZFS file systems.

| Requirements
| Experience using the Solaris Operating System (OS) or another UNIX® version is recommended.
|===

=== OpenSolaris Automated Installer Guide

[cols="1,4"]
|===

| Document Link
| link:./20090715/AIinstall/html/solarisinstall.html[OpenSolaris Automated Installer Guide]

| Topics
| If you want to install the OpenSolaris operating system (OS) on multiple client systems on a network, you can use the automated installer (AI) to accomplish that task.
The automated installer performs essentially “hands-free” network installations of the OpenSolaris OS.

| Relevancy to OpenIndiana Hipster
| < placeholder for content>

| Target Audience
| This book is intended for anyone responsible for administering one or more systems that are running the Solaris release.

| Requirements
| Experience using the Solaris Operating System (OS) or another UNIX® version is recommended.
|===

=== System Administration Guide: Advanced Administration

[cols="1,4"]
|===

| Document Link
| link:./20090715/SYSADV2/html/sysadv2.html[System Administration Guide: Advanced Administration]

| Topics
a| - Terminals and modems
- System resources (disk quotas, accounting, and crontabs)
- System processes
- Troubleshooting Solaris software problems

| Relevancy to OpenIndiana Hipster
| < placeholder for content>

| Target Audience
| This book is intended for anyone responsible for administering one or more systems that are running the Solaris release.

| Requirements
| This book assumes that you have installed the SunOS™ Solaris Operating System.
It also assumes that you have set up any networking software that you plan to use.
To use this book, you should have 1-2 years of UNIX® system administration experience.
Attending UNIX system administration training courses might be helpful.
|===


=== System Administration Guide: Devices and File Systems

[cols="1,4"]
|===

| Document Link
| link:./20090715/SAGDFS/html/sagdfs.html[System Administration Guide: Devices and File Systems]

| Topics
a| - Removable media
- Disks and devices
- File systems
- Backing up and restoring data

| Relevancy to OpenIndiana Hipster
| < placeholder for content>

| Target Audience
| This book is intended for anyone responsible for administering one or more systems running the Solaris release.

| Requirements
| This book assumes you have installed the SunOS 5.11 Operating System and set up all the networking software that you plan to use.
To use this book, you should have 1–2 years of UNIX® system administration experience.
Attending UNIX system administration training courses might be helpful.
|===

=== System Administration Guide: IP Services

[cols="1,4"]
|===

| Document Link
| link:./20090715/SYSADV3/html/sysadv3.html[System Administration Guide: IP Services]

| Topics
a| - TCP/IP network administration
- IPv4 and IPv6 address administration
- DHCP
- IPsec
- IKE
- Solaris IP filter
- Mobile IP
- IP network multipathing (IPMP)
- IPQoS

| Relevancy to OpenIndiana Hipster
| < placeholder for content>

| Target Audience
| This book is intended for anyone responsible for administering systems that run the Solaris OS release, which are configured in a network.

| Requirements
| This book assumes that you have already installed the Solaris operating system (Solaris OS).
You should be ready to configure your network or ready to configure any networking software that is required on your network.
To use this book, you should have at least two years of UNIX® system administration experience.
Attending UNIX system administration training courses might be helpful.
|===


=== System Administration Guide: Network Services

[cols="1,4"]
|===

| Document Link
| link:./20090715/SYSADV4/html/sysadv4.html[System Administration Guide: Network Services]

| Topics
a| - Web cache servers
- Time-related services
- Network file systems (NFS and Autofs)
- Mail
- SLP
- PPP

| Relevancy to OpenIndiana Hipster
| < placeholder for content>

| Target Audience
| This book is intended for anyone responsible for administering one or more systems that run the Solaris 10 release.

| Requirements
| This book assumes that you have already installed the SunOS™ 5.10 operating system, and you have set up any networking software that you plan to use.
To use this book, you should have one to two years of UNIX® system administration experience.
Attending UNIX system administration training courses might be helpful.
|===


=== System Administration Guide: Naming and Directory Services (DNS, NIS, and LDAP)

[cols="1,4"]
|===

| Document Link
| link:./20090715/SYSADV5/html/sysadv5.html[System Administration Guide: Naming and Directory Services (DNS, NIS, and LDAP)]

| Topics
a| - DNS
- NIS
- LDAP (including transitioning from NIS to LDAP and transitioning from NIS+ to LDAP)

| Relevancy to OpenIndiana Hipster
| < placeholder for content>

| Target Audience
| This manual is written for experienced system and network administrators.

| Requirements
| Although this book introduces networking concepts relevant to Solaris naming and directory services, it explains neither the networking fundamentals nor the administration tools in the Solaris OS.
To use this book, you should have a firm understanding of UNIX® networking and systems administration fundamentals.
|===


=== System Administration Guide: Solaris Printing

[cols="1,4"]
|===

| Document Link
| link:./20090715/SYSADPRTSVCS/html/sysadprtsvcs.html[System Administration Guide: Solaris Printing]

| Topics
a| - Solaris printing topics and tasks
- Using services, tools, protocols, and technologies to set up and administer printing services and printers

| Relevancy to OpenIndiana Hipster
| < placeholder for content>

| Target Audience
| This book is intended for anyone responsible for administering one or more systems that are running the Solaris release.

| Requirements
| This book assumes that you have installed the SunOS™ Solaris Operating System.
It also assumes that you have set up any networking software that you plan to use.
To use this book, you should have 1-2 years of UNIX® system administration experience.
Attending UNIX system administration training courses might be helpful.
|===


=== System Administration Guide: Security Services

[cols="1,4"]
|===

| Document Link
| link:./20090715/SYSADV6/html/sysadv6.html[System Administration Guide: Security Services]

| Topics
a| - Auditing
- Device management
- File security
- BART
- Kerberos services
- PAM
- Solaris Cryptographic Framework
- Privileges
- RBAC
- SASL
- Solaris Secure Shell

| Relevancy to OpenIndiana Hipster
| < placeholder for content>

| Target Audience
| This book is intended for anyone who is responsible for administering one or more systems that run a Solaris Express Community Edition release.

| Requirements
| To use this book, you should have more than two years of UNIX® system administration experience.
Attending training courses in UNIX system administration might be helpful.
|===

=== System Administration Guide: Virtualization Using the Solaris Operating System

[cols="1,4"]
|===

| Document Link
| link:./20090715/SYSADRM/html/sysadrm.html[System Administration Guide: Virtualization Using the Solaris Operating System]

| Topics
a| - Resource management features, which enable you to control how applications use available system resources
- Zones software partitioning technology, which virtualizes operating system services to create an isolated environment for running applications
- Virtualization using Sun™ xVM hypervisor technology, which supports multiple operating system instances simultaneously

| Relevancy to OpenIndiana Hipster
| < placeholder for content>

| Target Audience
| This book is intended for anyone responsible for administering one or more systems that run the Solaris release.

| Requirements
| This book assumes that you have already installed the operating system and set up any networking software that you plan to use.
To use this book, you should have at least one to two years of UNIX® system administration experience.
|===

=== Solaris Volume Manager Administration Guide

[cols="1,4"]
|===

| Document Link
| link:./20090715/LOGVOLMGRADMIN/html/logvolmgradmin.html[Solaris Volume Manager Administration Guide]

| Topics
| The Solaris Volume Manager Administration Guide explains how to use Solaris™ Volume Manager to manage your system's storage needs.
Solaris Volume Manager enables you to create, modify, and use RAID-0 (concatenation and stripe) volumes, RAID-1 (mirror) volumes.

| Relevancy to OpenIndiana Hipster
| < placeholder for content>

| Target Audience
a| System and storage administrators can use this book to identify:

- Tasks supported by Solaris Volume Manager
- Ways to use Solaris Volume Manager to provide more reliable and accessible data

| Requirements
| This book assumes that you have installed the SunOS™ Solaris Operating System.
It also assumes that you have set up any networking software that you plan to use.
To use this book, you should have 1-2 years of UNIX® system administration experience.
Attending UNIX system administration training courses might be helpful.
|===


=== Solaris Tunable Parameters Reference Manual

[cols="1,4"]
|===

| Document Link
| link:./20090715/SOLTUNEPARAMREF/html/soltuneparamref.html[Solaris Tunable Parameters Reference Manual]

| Topics
| The Solaris Tunable Parameters Reference Manual provides reference information about Solaris™ OS kernel and network tunable parameters.
This manual does not provide tunable parameter information about the CDE, GNOME, or Java™ environments.

| Relevancy to OpenIndiana Hipster
| < placeholder for content>

| Target Audience
| This book is intended for experienced Solaris system administrators who might need to change kernel tunable parameters in certain situations.

| Requirements
| To use this book, you should have more than two years of UNIX® system administration experience.
Attending training courses in UNIX system administration might be helpful.
|===


== Solaris Express Systems Administration


=== Solaris Express Developer Edition What's New

[cols="1,4"]
|===

| Document Link
| link:./20090715/SOLWHATSNEW/html/solwhatsnew.html[Solaris Express Developer Edition What's New]

| Topics
| Solaris Express Developer Edition What's New summarizes all features in the most current Software Express release.

| Relevancy to OpenIndiana Hipster
| < placeholder for content>

| Target Audience
| This book provides introductory descriptions of the new Software Express features for users, developers, and system administrators.

| Requirements
| To use this book, you should have 1-2 years of UNIX® system administration experience.
Attending UNIX system administration training courses might be helpful.
|===


=== Solaris Express Developer Edition Release Notes

[cols="1,4"]
|===

| Document Link
| link:./20090715/SOLDEVERN/html/soldevern.html[Solaris Express Developer Edition Release Notes]

| Topics
| The Solaris Express Developer Edition Release Notes contains installation and runtime problem details.
Also included are end-of-software support statements for the Solaris™ Operating System (Solaris OS).

| Relevancy to OpenIndiana Hipster
| < placeholder for content>

| Target Audience
| These notes are for users and system administrators who install and use the Solaris Operating System.

| Requirements
| To use this book, you should have 1-2 years of UNIX® system administration experience.
Attending UNIX system administration training courses might be helpful.
|===


=== Solaris Express Installation Guide: Planning for Installation and Upgrade

[cols="1,4"]
|===

| Document Link
| link:./20090715/SOLINSTALLPBIU/html/solinstallpbiu.html[Solaris Express Installation Guide: Planning for Installation and Upgrade]

| Topics
| This book describes planning your installation or upgrade with the Solaris™ Operating System (OS) on both networked and nonnetworked SPARC® and x86 architecture based systems.
This book also provides overviews of several technologies that relate to installation such as Solaris Zones, GRUB based booting, and the creation of RAID-1 volumes during installation.

This book does not include instructions about how to set up system hardware or other peripherals.

| Relevancy to OpenIndiana Hipster
| < placeholder for content>

| Target Audience
a| This book is intended for system administrators responsible for installing the Solaris OS.

This book provides both of the following types of information.

* Advanced Solaris installation planning information for enterprise system administrators who manage multiple Solaris machines in a networked environment
* Basic Solaris installation planning information for system administrators who perform infrequent Solaris installations or upgrades

| Requirements
| To use this book, you should have 1-2 years of UNIX® system administration experience.
Attending UNIX system administration training courses might be helpful.
|===


=== Solaris Express Installation Guide: Basic Installations

[cols="1,4"]
|===

| Document Link
| link:./20090715/SOLARISINSTALL/html/solarisinstall.html[Solaris Express Installation Guide: Basic Installations]

| Topics
| This book describes how to use CD or DVD media to install the Solaris™ Operating System (Solaris OS) on a non-networked system.

This book does not include instructions about how to set up system hardware or other peripherals.

| Relevancy to OpenIndiana Hipster
| < placeholder for content>

| Target Audience
| This book is intended for system administrators who are responsible for installing the Solaris OS.
This book provides basic Solaris installation information for system administrators who perform infrequent Solaris installations or upgrades.

| Requirements
| To use this book, you should have 1-2 years of UNIX® system administration experience.
Attending UNIX system administration training courses might be helpful.
|===


=== Solaris Express Developer Edition Installation Guide: Laptop Installations

[cols="1,4"]
|===

| Document Link
| link:./20090715/SOLDEVELINSTALL/html/soldevelinstall.html[Solaris Express Developer Edition Installation Guide: Laptop Installations]

| Topics
| This book provides general guidance for installing the Solaris Express Developer Edition on a laptop computer.

| Relevancy to OpenIndiana Hipster
| < placeholder for content>

| Target Audience
| This book is intended for anyone interested in installing Solaris Express Developer Edition on laptop hardware.

| Requirements
| To use this book, you should have basic UNIX® system administration experience.
Attending UNIX system administration training courses might be helpful.
|===


=== Solaris Express Installation Guide: Network-Based Installations

[cols="1,4"]
|===

| Document Link
| link:./20090715/SOLINSTALLNET/html/solinstallnet.html[Solaris Express Installation Guide: Network-Based Installations]

| Topics
| This book describes how to install the Solaris™ Operating System (Solaris OS) remotely over a local area network or a wide area network.

This book does not include instructions about how to set up system hardware or other peripherals.

| Relevancy to OpenIndiana Hipster
| < placeholder for content>

| Target Audience
| This book is intended for system administrators who are responsible for installing the Solaris software.
This book provides advanced Solaris installation information for enterprise system administrators who manage multiple Solaris machines in a networked environment.

| Requirements
| To use this book, you should have 1-2 years of UNIX® system administration experience.
Attending UNIX system administration training courses might be helpful.
|===


=== Solaris Express Installation Guide: Solaris Flash Archives (Creation and Installation)

[cols="1,4"]
|===

| Document Link
| link:./20090715/SOLINSTALLFLASH/html/solinstallflash.html[Solaris Express Installation Guide: Solaris Flash Archives (Creation and Installation)]

| Topics
| This book provides planning information and instructions for creating Solaris™ Flash archives and using Solaris Flash archives to install the Solaris Operating System (OS) on multiple systems.

This book does not include instructions about how to set up system hardware or other peripherals.

| Relevancy to OpenIndiana Hipster
| < placeholder for content>

| Target Audience
| This book is intended for system administrators who are responsible for installing the Solaris OS.
These procedures are advanced Solaris installation information for enterprise system administrators who manage multiple Solaris machines in a networked environment.

| Requirements
| To use this book, you should have 2 or more years of UNIX® system administration experience.
Attending UNIX system administration training courses might be helpful.
|===

=== Solaris Express Installation Guide: Solaris Live Upgrade and Upgrade Planning

[cols="1,4"]
|===

| Document Link
| link:./20090715/SOLINSTALLUPG/html/solinstallupg.html[Solaris Express Installation Guide: Solaris Live Upgrade and Upgrade Planning]

| Topics
| This book describes how to install and upgrade the Solaris™ Operating System (OS) on both networked and nonnetworked SPARC® and x86 architecture based systems.

This book does not include instructions about how to set up system hardware or other peripherals.

| Relevancy to OpenIndiana Hipster
| < placeholder for content>

| Target Audience
a| This book is intended for system administrators responsible for installing the Solaris OS.
This book provides both of the following types of information.

- Advanced Solaris installation information for enterprise system administrators who manage multiple Solaris machines in a networked environment
- Basic Solaris installation information for system administrators who perform infrequent Solaris upgrades

| Requirements
| To use this book, you should have 2 or more years of UNIX® system administration experience.
Attending UNIX system administration training courses might be helpful.
|===


=== Solaris Express Installation Guide: Custom JumpStart and Advanced Installations

[cols="1,4"]
|===

| Document Link
| link:./20090715/SOLINSTALLADV/html/solinstalladv.html[Solaris Express Installation Guide: Custom JumpStart and Advanced Installations]

| Topics
| This book describes how to install and upgrade the Solaris™ Operating System (OS) on both networked and nonnetworked SPARC® and x86 architecture based systems.
This book covers using the custom JumpStart installation method and the creation of RAID-1 volumes during installation.

This book does not include instructions about how to set up system hardware or other peripherals.

| Relevancy to OpenIndiana Hipster
| < placeholder for content>

| Target Audience
a| This book is intended for system administrators responsible for installing the Solaris OS.
This book provides both of the following types of information.

- Advanced Solaris installation information for enterprise system administrators who manage multiple Solaris machines in a networked environment
- Basic Solaris installation information for system administrators who perform infrequent Solaris installations or upgrades

| Requirements
| To use this book, you should have 2 or more years of UNIX® system administration experience.
Attending UNIX system administration training courses might be helpful.
|===


=== Solaris Express Package List

[cols="1,4"]
|===

| Document Link
| link:./20090715/INSTALLPKGLIST/html/installpkglist.html[Solaris Express Package List]

| Topics
| The Solaris Express Package List lists and describes the packages included in the Solaris™ Express Operating System (Solaris OS).
The list includes information about the software groups that contain each package.

| Relevancy to OpenIndiana Hipster
| < placeholder for content>

| Target Audience
| This book is intended for system administrators responsible for installing the Solaris software.

| Requirements
| To use this book, you should have 1-2 years of UNIX® system administration experience.
Attending UNIX system administration training courses might be helpful.
|===


== Trusted Extensions Systems Administration


=== Solaris Trusted Extensions Installation and Configuration

.Document Link
link:./20090715/TRSOLINSTALL/html/trsolinstall.html[Solaris Trusted Extensions Installation and Configuration]

.Topics

*Obsolete.*

Describes how to plan for, install, and configure Solaris Trusted Extensions for the Solaris 10 11/06 and Solaris 10 8/07 releases of Trusted Extensions.

The Solaris Trusted Extensions Installation and Configuration guide provides procedures for configuring Solaris™ Trusted Extensions on the Solaris Operating System.
This guide also describes preparing the Solaris system to support a secure installation of Solaris Trusted Extensions.

.Target Audience
Administrators, developers

This book is for knowledgeable system administrators and security administrators who are installing Trusted Extensions software.
The level of trust that is required by your site security policy, and your level of expertise, determines who can perform the configuration tasks.

.Requirements
Successfully configuring Trusted Extensions on a system in a way that is consistent with site security requires understanding the security features of Trusted Extensions and your site security policy. 
Before you install the Solaris Trusted Extensions packages, read _Chapter 1, Security Planning for Trusted Extensions_ for information about how to ensure site security when configuring the software.

=== Solaris Trusted Extensions User's Guide

.Document Link
link:./20090715/TRSSUG/html/trssug.html[Solaris Trusted Extensions User's Guide]

.Topics
Describes the basic features of Solaris Trusted Extensions.
This book contains a glossary.

The Solaris Trusted Extensions User's Guide is a guide to working in the Solaris™ Operating System (Solaris OS) with Solaris Trusted Extensions installed.

.Target Audience
This book is for all users of Trusted Extensions.

End users, administrators, developers

.Requirements

As a prerequisite, you must be familiar with the Solaris OS and one of the following desktops:

- Common Desktop Environment (CDE)
- The open source GNOME desktop
- Sun Java™ Desktop System

You must also be familiar with the security policy of your organization.


=== Solaris Trusted Extensions Administrator's Procedures

.Document Link
link:./20090715/TRSOLADMPROC/html/trsoladmproc.html[Solaris Trusted Extensions Administrator's Procedures]

.Topics
For this release, Part I describes how to prepare for, enable, and initially configure Trusted Extensions.
Part I replaces Solaris Trusted Extensions Installation and Configuration.

Part II describes how to administer a Trusted Extensions system.
This book contains a glossary.

System installation, configuration, and administration that is specific to Solaris Trusted Extensions

.Target Audience
Administrators, developers

This book is for knowledgeable system administrators and security administrators who are configuring and administering Trusted Extensions software.
The level of trust that is required by your site security policy, and your level of expertise, determines who can perform the configuration tasks.

.Reguirements
Administrators should be familiar with Solaris administration.
In addition, administrators should understand the following:

- The security features of Trusted Extensions and your site security policy
- Basic concepts and procedures for using a host that is configured with Trusted Extensions, as described in the Solaris Trusted Extensions User’s Guide
- How administrative tasks are divided among roles at your site


=== Solaris Trusted Extensions Label Administration

.Document Link
link:./20090715/TRSOLLBLADMIN/html/trsollbladmin.html[Solaris Trusted Extensions Label Administration]

.Topics
Provides information about how to specify label components in the label encodings file.

Labels, clearances, and handling instructions are used to protect information on a system that is configured with Solaris Trusted Extensions software.
The components of labels, clearances, and handling instructions are specified in the `label_encodings` file.
This guide provides background for creating or modifying the file.
The guide provides examples, and helps you to create and install a `label_encodings` file that is appropriate for your site.

.Target Audience
Administrators

This book is for security administrators.
Security administrators are responsible for defining the organization's labels.
Some security administrators are also responsible for implementing the labels.
This book is for definers and implementers.

.Requirements
The security administrator who implements the labels should be familiar with Solaris administration.
The necessary level of knowledge can be acquired through training and documentation. 

=== Solaris Trusted Extensions Transition Guide

.Document Link
link:./20090715/TRSOLTRANS/html/trsoltrans.html[Solaris Trusted Extensions Transition Guide]

.Topics

The Solaris Trusted Extensions Transition Guide describes the differences between the Solaris Trusted Extensions release and the following releases:

The Trusted Solaris™ 8 releases

The Solaris™ 10 Operating System release

The differences include labels, a modified desktop, a modified windowing system, and modified administration tools.

.Target Audience

All users should find the book useful.
The Solaris Trusted Extensions Transition Guide is designed for users who are familiar with Trusted Solaris releases and with the Solaris OS.
This book enables these users to more easily use systems that are configured with Solaris Trusted Extensions.

.Requirements

< place holder >

== Development


=== Solaris Dynamic Tracing Guide

.Document Link
link:./20090715/DYNMCTRCGGD/html/dynmctrcggd.html[Solaris Dynamic Tracing Guide]

.Topics
DTrace is a comprehensive dynamic tracing framework for the Solaris™ Operating System.
DTrace provides a powerful infrastructure to permit administrators, developers, and service personnel to concisely answer arbitrary questions about the behavior of the operating system and user programs.
The Solaris Dynamic Tracing Guide describes how to use DTrace to observe, debug, and tune system behavior.
This book also includes a complete reference for bundled DTrace observability tools and the D programming language.

.Target Audience
If you have ever wanted to understand the behavior of your system, DTrace is the tool for you.
DTrace is a comprehensive dynamic tracing facility that is built into Solaris.
The DTrace facility can be used to examine the behavior of user programs.
The DTrace facility can also be used to examine the behavior of the operating system.
DTrace can be used by system administrators or application developers, and is suitable for use with live production systems.
DTrace will allow you to explore your system to understand how it works, track down performance problems across many layers of software, or locate the cause of aberrant behavior.
As you'll see, DTrace lets you create your own custom programs to dynamically instrument the system and provide immediate, concise answers to arbitrary questions you can formulate using the DTrace D programming language.

DTrace allows all Solaris users to:

- Dynamically enable and manage thousands of probes
- Dynamically associate logical predicates and actions with probes
- Dynamically manage trace buffers and buffer policies
- Display and examine trace data from the live system or a crash dump

DTrace allows Solaris developers and administrators to:

- Implement custom scripts that use the DTrace facility
- Implement layered tools that use DTrace to retrieve trace data

.Requirements
Basic familiarity with a programming language such as C or a scripting language such as `awk(1)` or `perl(1)` will help you learn DTrace and the D programming language faster, but you need not be an expert in any of these areas.
If you have never written a program or script before in any language, Related Information provides references to other documents you might find useful.


=== Solaris Modular Debugger Guide

.Document Link
link:./20090715/MODDEBUG/html/moddebug.html[Solaris Modular Debugger Guide]

.Topics
The Modular Debugger (MDB) is a highly extensible, general purpose debugging tool for the Solaris™ Operating System (Solaris OS).
The Solaris Modular Debugger Guide describes how to use MDB to debug complex software systems, with a particular emphasis on the facilities available for debugging the Solaris kernel and associated device drivers and modules.
It also includes a complete reference for and discussion of the MDB language syntax, debugger features, and MDB Module Programming API.

.Target Audience
If you were a detective and were investigating at the scene of a crime, you might interview the witnesses and ask them to describe what happened and who they saw.
However, if there were no witnesses or these descriptions proved insufficient, you might consider collecting fingerprints and forensic evidence that could be examined for DNA to help solve the case.
Often, software program failures divide into analogous categories: problems that can be solved with source-level debugging tools, and problems that require low-level debugging facilities, examination of core files, and knowledge of assembly language to diagnose and correct.
MDB facilitates analysis of this second class of problems.

MDB is most useful when you are programming a complex low-level software system such as an operating system.
The MDB debugging framework allows you to construct your own custom analysis tools to aid in the diagnosis of these low-level problems.
MDB also provides a powerful set of built-in commands that enable you to analyze the state of your program at the assembly language level.

.Requirements
Familarity with assembly language programming and debugging

=== Device Driver Tutorial

.Document Link
link:./20090715/DRIVERTUT/html/drivertut.html[Device Driver Tutorial]

.Topics
This Device Driver Tutorial is a hands-on guide that shows you how to develop a simple device driver for the Solaris™ Operating System (Solaris OS).
Device Driver Tutorial also explains how device drivers work in the Solaris OS.
This book is a companion to _Writing Device Drivers_.
_Writing Device Drivers_ is a thorough reference document that discusses many types of devices and drivers.
Device Driver Tutorial examines complete drivers but does not provide a comprehensive treatment of all driver types.
Device Driver Tutorial often points to Writing Device Drivers and other books for further information.

.Target Audience
You should read this tutorial if you need to develop, install, and configure device drivers for the Solaris OS.
You also should read this book if you need to maintain existing drivers or add new functionality to existing Solaris OS drivers.
Information about the kernel provided in this book also will help you troubleshoot any problems you might encounter installing or configuring Solaris systems.

.Requirements
To write device drivers for the Solaris OS, you should have the following background:

- Be a confident C programmer
- Have experience with data structures, especially with linked lists
- Understand bit operations
- Understand indirect function calls
- Understand caching
- Understand multithreading (see the Multithreaded Programming Guide)
- Be familiar with a UNIX® shell
- Understand the basics of UNIX system and I/O architecture

The most important information you need to have to write a device driver are the characteristics of the device. 
Get a detailed specification for the device you want to drive.

Experience with Solaris OS compilers, debuggers, and other tools will be very helpful to you.
You also need to understand where the file system fits with the kernel and the application layer.
These topics are discussed in this tutorial.


=== Writing Device Drivers

.Document Link
link:./20090715/DRIVER/html/driver.html[Writing Device Drivers]

.Topics
Writing Device Drivers provides information on developing drivers for character-oriented devices, block-oriented devices, network devices, SCSI target and HBA devices, and USB devices for the Solaris™ Operating System (Solaris OS).
This book discusses how to develop multithreaded reentrant device drivers for all architectures that conform to the Solaris OS DDI/DKI (Device Driver Interface, Driver-Kernel Interface). A common driver programming approach is described that enables drivers to be written without concern for platform-specific issues such as endianness and data ordering.

Additional topics include hardening Solaris drivers; power management; driver autoconfiguration; programmed I/O; Direct Memory Access (DMA); device context management; compilation, installation, and testing drivers; debugging drivers; and porting Solaris drivers to a 64-bit environment.

.Target Audience
This book is written for UNIX® programmers who are familiar with UNIX device drivers.
Overview information is provided, but the book is not intended to serve as a general tutorial on device drivers.

.Requirements

< Place Holder >

=== Application Packaging Developer's Guide

.Document Link
link:./20090715/PACKINSTALL/html/packinstall.html[Application Packaging Developer's Guide]

.Topics
The Application Packaging Developer’s Guide provides step-by-step instructions and relevant background information for designing, building, and verifying packages.
This guide also includes advanced techniques that you might find helpful during the package creation process.

.Target Audience
This book is intended for application developers whose responsibilities include designing and building packages.
Though much of the book is directed towards novice package developers, it also contains information useful to more experienced package developers.

.Requirements

< Place Holder >


=== OpenSolaris Distribution Constructor Guide

.Document Link
link:./20090715/DistroConst/html/distroconst.html[OpenSolaris Distribution Constructor Guide]

.Topics
The distribution constructor is a tool that application developers can use to build their own custom OpenSolaris™ image which they can then distribute to their contacts and customers.

.Target Audience

< Place Holder >

.Requirements

< Place Holder >

=== Memory and Thread Placement Optimization Developer's Guide

.Document Link
link:./20090715/MTPODG/html/mtpodg.html[Memory and Thread Placement Optimization Developer's Guide]

.Topics
The Memory and Thread Placement Optimization Developer's Guide provides information on locality groups and the technologies that are available to optimize the use of computing resources in the Solaris operating system.

.Target Audience
This book is intended for use by developers who are writing applications in an environment with multiple CPUs and a non-uniform memory architecture.
The programming interfaces and tools that are described in this book give the developer control over the system's behavior and resource allocation.

.Requirements

< Place Holder >



=== Solaris Containers: Resource Management and Solaris Zones Developer's Guide

.Document Link
link:./20090715/RSCMGRDEVGD/html/rscmgrdevgd.html[Solaris Containers: Resource Management and Solaris Zones Developer's Guide]

.Topics
The Solaris Containers: Resource Management and Solaris Zones Developer's Guide describes how to write applications that partition and manage system resources and discusses which APIs to use.
This book provides programming examples and a discussion of programming issues to consider when writing an application.

.Target Audience
This book is for application developers and ISVs who write applications that control or monitor the Solaris Operating System resources.

.Requirements

< Place Holder >



=== Solaris Trusted Extensions Developer's Guide

.Document Link
link:./20090715/TRSOLDEV/html/trsoldev.html[Solaris Trusted Extensions Developer's Guide]

.Topics
Describes how to develop applications with Solaris Trusted Extensions.

The Solaris Trusted Extensions Developer's Guide describes how to use the application programming interfaces (APIs) to write new trusted applications for systems that are configured with the Solaris™ Trusted Extensions software.

.Target Audience
Developers, administrators

.Requirements
Readers must be familiar with UNIX® programming and understand security policy concepts.


