// vim: set syntax=asciidoc:

// Start of document parameters

:icons: font
:sectnums:
:toc: left

// End of document parameters


.TODO
- Add a row to each table describing the relevancy of the book in relation to OpenIndiana Hipster.
* See the SmartOS wiki for an example of this where they compare various OSOL commercial books to illumos.




= OpenSolaris Redistributable Docs - 2009.07.15

Consisting of 41 titles and originally published on July 15th, 2009, this collection of books compose the final docs release of the OpenSolaris project.
For ease of use, the titles have been organized by subject matter and grouped according to their intended target audience.
For each title, a brief synopsis has been provided.
Otherwise, the books are exactly as originally published.
No editing of any kind has been performed on any of the titles.
This documentation collection has been released under the https://www.openoffice.org/licenses/PDL.html[Public Documentation License (PDL)].


[NOTE]
====
When using these books, please bear in mind:

- The OpenIndiana Project has republished these books primarily for their reference value.
- Although vast portions of these books are still revelant, significant divergence has occured between OpenIndiana Hipster and OpenSolaris/Solaris Express.
- Some of the books in this collection reference publications which were either never opensourced by Sun Microsystems or never released by the OpenSolaris Project.
  For example, the _OpenSolaris Developer's Reference Guide_ was never released as part of this collection.
- There are lots of broken links to OpenSolaris.org and Sun Microsystems.
- In some cases, it may be possible to follow broken links by using the https://archive.org/web/[Internet Archive Wayback Machine].
====

.Titles Updated by the illumos Project
Several of the development related titles were updated in the early days of the illumos project.
The illumos updated titles can be found here: https://illumos.org/books/

.The OpenIndiana Project's Documentation Update Effort
An effort currently exists within the OpenIndiana community to review the 2009.07.15 docs collection for updating.
If you wish to participate in this effort, please indicate your interest in one or more of the following ways:


|===
| Resource | URL

| User Support IRC channel
| irc://irc.freenode.net/openindiana[#openindiana on irc.freenode.net]

| Development IRC channel
| irc://irc.freenode.net/oi-dev[#oi-dev on irc.freenode.net]

| Documentation IRC channel
| irc://irc.freenode.net/oi-documentation[#oi-documentation on irc.freenode.net]

| OpenIndiana Mailing Lists
| http://openindiana.org/mailman
|===


== Basic Systems Administration


=== Getting Started with OpenSolaris

[cols="1,4"]
|===

| Document Link
| link:./20090715/getstart/html/solarisinstall.html[Getting Started With OpenSolaris]

| Topics
| The guide provides an introduction to the OpenSolaris™ operating system, as well as instructions for installing the current OpenSolaris release on your system.
This guide is intended to help you install and set up the free binary distribution of the OpenSolaris software and make your initial experience with it a successful one.

| Target Audience
| This book is intended for anyone interested in installing and exploring the OpenSolaris operating system.

| Requirements
| Experience using the Solaris Operating System (OS) or another UNIX® version is recommended.
|===


=== System Administration Guide: Basic Administration

[cols="1,4"]
|===

| Document Link 
| link:./20090715/SYSADV1/html/sysadv1.html[System Administration Guide: Basic Administration]

| Topics
a| - User accounts and groups +
- Server and client support +
- Shutting down and booting a system +
- Managing services +
- Managing software (packages and patches)

| Target Audience
| This book is intended for anyone responsible for administering one or more systems running the Solaris release.

| Requirements
| This book assumes you have installed the Solaris Express Operating System and set up all the networking software that you plan to use.
To use this book, you should have 1-2 years of UNIX® system administration experience.
Attending UNIX system administration training courses might be helpful.
|===

== Intermediate & Advanced Systems Administration


=== OpenSolaris Managing Boot Environments

[cols="1,4"]
|===

| Document Link
| link:./20090715/snapupgrade/html/solarisinstall.html[OpenSolaris Managing Boot Environments]

| Topics
| A boot environment is a bootable instance of an OpenSolarisTM operating system image plus any other application software packages installed into that image.
System administrators can maintain multiple boot environments on their systems, and each boot environment can have different software versions installed.

Upon the initial installation of OpenSolaris onto a system, a boot environment is created.
Use the beadm(1M) utility or the Package Manager to administer additional boot environments on your system.

| Target Audience
| This book is intended for anyone responsible for administering one or more systems running the OpenSolaris operating system.

| Requirements
| Experience using the Solaris Operating System (OS) or another UNIX® version is recommended.
|===


=== OpenSolaris 2009.06 Image Packaging System Guide

[cols="1,4"]
|===

| Document Link
| link:./20090715/IMGPACKAGESYS/html/ips.html[OpenSolaris 2009.06 Image Packaging System Guide]

| Topics
a| The Image Packaging System, pkg(5), is a framework that provides for software lifecycle management such as installation, upgrade, and removal of packages.
IPS also provides users the ability to create their own software packages, create and manage packaging repositories, and mirror existing packaging repositories.

With IPS, users can perform the following tasks:

- Create and manage images

- Install new packages and update existing packages

- Manage and search the software on your system

With the IPS publication tools, developers can perform the following:

- Create and manage packaging repositories

- Create and publish packages to a packaging repository

- Provide a content mirror for an existing packaging repository

- Retrieve the contents of an existing package from a packaging repository

- Republish the contents of an existing package to a packaging repository

| Target Audience
| This book is intended for system administrators, end users, and developers.

| Requirements
| Experience using the Solaris Operating System (OS) or another UNIX® version is recommended.
|===


=== Solaris CIFS Administration Guide

[cols="1,4"]
|===

| Document Link
| link:./20090715/SSMBAG/html/ssmbag.html[Solaris CIFS Administration Guide]

| Topics
a| - Solaris CIFS service, which enables you to configure a Solaris system to make CIFS shares available to CIFS clients.
- Native identity mapping services, which enables you to map user and group identities between Solaris systems and Windows systems.

| Target Audience
| This book is intended for system administrators and end users.
Both Solaris and Windows system administrators can use this information to configure and integrate the Solaris CIFS service into a Windows environment.

In addition, system administrators can configure the identity mapping service.
Finally, the chapter about the Solaris CIFS client is primarily intended for Solaris users who would like to mount CIFS shares.
The Solaris CIFS client chapter also includes tasks to be performed by a system administrator.

| Requirements
| Experience using the Solaris Operating System (OS) or another UNIX® version is recommended.
|===

=== Solaris ZFS Administration Guide

[cols="1,4"]
|===

| Document Link
| link:./20090715/ZFSADMIN/html/zfsadmin.html[Solaris ZFS Administration Guide]

| Topics
a| - ZFS storage pool and file system creation and management
- Snapshots
- Clones
- Backups
- Using access control lists (ACLs) to protect ZFS files
- Using ZFS on a Solaris system with zones installed
- Emulated volumes
- Troubleshooting
- Data recovery

| Target Audience
| This guide is intended for anyone who is interested in setting up and managing Solaris ZFS file systems.

| Requirements
| Experience using the Solaris Operating System (OS) or another UNIX® version is recommended.
|===

=== OpenSolaris Automated Installer Guide

[cols="1,4"]
|===

| Document Link
| link:./20090715/AIinstall/html/solarisinstall.html[OpenSolaris Automated Installer Guide]

| Topics
| If you want to install the OpenSolaris operating system (OS) on multiple client systems on a network, you can use the automated installer (AI) to accomplish that task.
The automated installer performs essentially “hands-free” network installations of the OpenSolaris OS.

| Target Audience
| This book is intended for anyone responsible for administering one or more systems that are running the Solaris release.

| Requirements
| Experience using the Solaris Operating System (OS) or another UNIX® version is recommended.
|===

=== System Administration Guide: Advanced Administration

[cols="1,4"]
|===

| Document Link
| link:./20090715/SYSADV2/html/sysadv2.html[System Administration Guide: Advanced Administration]

| Topics
a| - Terminals and modems
- System resources (disk quotas, accounting, and crontabs)
- System processes
- Troubleshooting Solaris software problems

| Target Audience
| This book is intended for anyone responsible for administering one or more systems that are running the Solaris release.

| Requirements
| This book assumes that you have installed the SunOS™ Solaris Operating System.
It also assumes that you have set up any networking software that you plan to use.
To use this book, you should have 1-2 years of UNIX® system administration experience.
Attending UNIX system administration training courses might be helpful.
|===


=== System Administration Guide: Devices and File Systems

[cols="1,4"]
|===

| Document Link
| link:./20090715/SAGDFS/html/sagdfs.html[System Administration Guide: Devices and File Systems]

| Topics
a| - Removable media
- Disks and devices
- File systems
- Backing up and restoring data

| Target Audience
| This book is intended for anyone responsible for administering one or more systems running the Solaris release.

| Requirements
| This book assumes you have installed the SunOS 5.11 Operating System and set up all the networking software that you plan to use.
To use this book, you should have 1–2 years of UNIX® system administration experience.
Attending UNIX system administration training courses might be helpful.
|===

=== System Administration Guide: IP Services

[cols="1,4"]
|===

| Document Link
| link:./20090715/SYSADV3/html/sysadv3.html[System Administration Guide: IP Services]

| Topics
a| - TCP/IP network administration
- IPv4 and IPv6 address administration
- DHCP
- IPsec
- IKE
- Solaris IP filter
- Mobile IP
- IP network multipathing (IPMP)
- IPQoS

| Target Audience
| This book is intended for anyone responsible for administering systems that run the Solaris OS release, which are configured in a network.

| Requirements
| This book assumes that you have already installed the Solaris operating system (Solaris OS).
You should be ready to configure your network or ready to configure any networking software that is required on your network.
To use this book, you should have at least two years of UNIX® system administration experience.
Attending UNIX system administration training courses might be helpful.
|===


=== System Administration Guide: Network Services

[cols="1,4"]
|===

| Document Link
| link:./20090715/SYSADV4/html/sysadv4.html[System Administration Guide: Network Services]

| Topics
a| - Web cache servers
- Time-related services
- Network file systems (NFS and Autofs)
- Mail
- SLP
- PPP

| Target Audience
| This book is intended for anyone responsible for administering one or more systems that run the Solaris 10 release.

| Requirements
| This book assumes that you have already installed the SunOSTM 5.10 operating system, and you have set up any networking software that you plan to use.
To use this book, you should have one to two years of UNIX® system administration experience.
Attending UNIX system administration training courses might be helpful.
|===


=== System Administration Guide: Naming and Directory Services (DNS, NIS, and LDAP)

[cols="1,4"]
|===

| Document Link
| link:./20090715/SYSADV5/html/sysadv5.html[System Administration Guide: Naming and Directory Services (DNS, NIS, and LDAP)]

| Topics
a| - DNS
- NIS
- LDAP (including transitioning from NIS to LDAP and transitioning from NIS+ to LDAP)

| Target Audience
| This manual is written for experienced system and network administrators.

| Requirements
| Although this book introduces networking concepts relevant to Solaris naming and directory services, it explains neither the networking fundamentals nor the administration tools in the Solaris OS.
To use this book, you should have a firm understanding of UNIX® networking and systems administration fundamentals.
|===


=== System Administration Guide: Solaris Printing

[cols="1,4"]
|===

| Document Link
| link:./20090715/SYSADPRTSVCS/html/sysadprtsvcs.html[System Administration Guide: Solaris Printing]

| Topics
a| - Solaris printing topics and tasks
- Using services, tools, protocols, and technologies to set up and administer printing services and printers

| Target Audience
| This book is intended for anyone responsible for administering one or more systems that are running the Solaris release.

| Requirements
| This book assumes that you have installed the SunOSTM Solaris Operating System.
It also assumes that you have set up any networking software that you plan to use.
To use this book, you should have 1-2 years of UNIX® system administration experience.
Attending UNIX system administration training courses might be helpful.
|===


=== System Administration Guide: Security Services

[cols="1,4"]
|===

| Document Link
| link:./20090715/SYSADV6/html/sysadv6.html[System Administration Guide: Security Services]

| Topics
a| - Auditing
- Device management
- File security
- BART
- Kerberos services
- PAM
- Solaris Cryptographic Framework
- Privileges
- RBAC
- SASL
- Solaris Secure Shell

| Target Audience
| This book is intended for anyone who is responsible for administering one or more systems that run a Solaris Express Community Edition release.

| Requirements
| To use this book, you should have more than two years of UNIX® system administration experience.
Attending training courses in UNIX system administration might be helpful.
|===

=== System Administration Guide: Virtualization Using the Solaris Operating System

[cols="1,4"]
|===

| Document Link
| link:./20090715/SYSADRM/html/sysadrm.html[System Administration Guide: Virtualization Using the Solaris Operating System]

| Topics
a| - Resource management features, which enable you to control how applications use available system resources
- Zones software partitioning technology, which virtualizes operating system services to create an isolated environment for running applications
- Virtualization using SunTM xVM hypervisor technology, which supports multiple operating system instances simultaneously

| Target Audience
| This book is intended for anyone responsible for administering one or more systems that run the Solaris release.

| Requirements
| This book assumes that you have already installed the operating system and set up any networking software that you plan to use.
To use this book, you should have at least one to two years of UNIX® system administration experience.
|===

=== Solaris Volume Manager Administration Guide

[cols="1,4"]
|===

| Document Link
| link:./20090715/LOGVOLMGRADMIN/html/logvolmgradmin.html[Solaris Volume Manager Administration Guide]

| Topics
| The Solaris Volume Manager Administration Guide explains how to use Solaris™ Volume Manager to manage your system's storage needs.
Solaris Volume Manager enables you to create, modify, and use RAID-0 (concatenation and stripe) volumes, RAID-1 (mirror) volumes.

| Target Audience
a| System and storage administrators can use this book to identify:

- Tasks supported by Solaris Volume Manager
- Ways to use Solaris Volume Manager to provide more reliable and accessible data

| Requirements
| This book assumes that you have installed the SunOSTM Solaris Operating System.
It also assumes that you have set up any networking software that you plan to use.
To use this book, you should have 1-2 years of UNIX® system administration experience.
Attending UNIX system administration training courses might be helpful.
|===


=== Solaris Tunable Parameters Reference Manual

[cols="1,4"]
|===

| Document Link
| link:./20090715/SOLTUNEPARAMREF/html/soltuneparamref.html[Solaris Tunable Parameters Reference Manual]

| Topics
| The Solaris Tunable Parameters Reference Manual provides reference information about SolarisTM OS kernel and network tunable parameters.
This manual does not provide tunable parameter information about the CDE, GNOME, or JavaTM environments.

| Target Audience
| This book is intended for experienced Solaris system administrators who might need to change kernel tunable parameters in certain situations.

| Requirements
| To use this book, you should have more than two years of UNIX® system administration experience.
Attending training courses in UNIX system administration might be helpful.
|===


== Solaris Express Systems Administration


=== Solaris Express Developer Edition What's New

[cols="1,4"]
|===

| Document Link
| link:./20090715/SOLWHATSNEW/html/solwhatsnew.html[Solaris Express Developer Edition What's New]

| Topics
| Solaris Express Developer Edition What's New summarizes all features in the most current Software Express release.

| Target Audience
| This book provides introductory descriptions of the new Software Express features for users, developers, and system administrators.

| Requirements
| To use this book, you should have 1-2 years of UNIX® system administration experience.
Attending UNIX system administration training courses might be helpful.
|===


=== Solaris Express Developer Edition Release Notes

[cols="1,4"]
|===

| Document Link
| link:./20090715/SOLDEVERN/html/soldevern.html[Solaris Express Developer Edition Release Notes]

| Topics
| The Solaris Express Developer Edition Release Notes contains installation and runtime problem details.
Also included are end-of-software support statements for the SolarisTM Operating System (Solaris OS).

| Target Audience
| These notes are for users and system administrators who install and use the Solaris Operating System.

| Requirements
| To use this book, you should have 1-2 years of UNIX® system administration experience.
Attending UNIX system administration training courses might be helpful.
|===


=== Solaris Express Installation Guide: Planning for Installation and Upgrade

[cols="1,4"]
|===

| Document Link
| link:./20090715/SOLINSTALLPBIU/html/solinstallpbiu.html[Solaris Express Installation Guide: Planning for Installation and Upgrade]

| Topics
| This book describes planning your installation or upgrade with the Solaris™ Operating System (OS) on both networked and nonnetworked SPARC® and x86 architecture based systems.
This book also provides overviews of several technologies that relate to installation such as Solaris Zones, GRUB based booting, and the creation of RAID-1 volumes during installation.

This book does not include instructions about how to set up system hardware or other peripherals.

| Target Audience
a| This book is intended for system administrators responsible for installing the Solaris OS.

This book provides both of the following types of information.

* Advanced Solaris installation planning information for enterprise system administrators who manage multiple Solaris machines in a networked environment
* Basic Solaris installation planning information for system administrators who perform infrequent Solaris installations or upgrades

| Requirements
| To use this book, you should have 1-2 years of UNIX® system administration experience.
Attending UNIX system administration training courses might be helpful.
|===


=== Solaris Express Installation Guide: Basic Installations

[cols="1,4"]
|===

| Document Link
| link:./20090715/SOLARISINSTALL/html/solarisinstall.html[Solaris Express Installation Guide: Basic Installations]

| Topics
| This book describes how to use CD or DVD media to install the Solaris™ Operating System (Solaris OS) on a non-networked system.

This book does not include instructions about how to set up system hardware or other peripherals.

| Target Audience
| This book is intended for system administrators who are responsible for installing the Solaris OS.
This book provides basic Solaris installation information for system administrators who perform infrequent Solaris installations or upgrades.

| Requirements
| To use this book, you should have 1-2 years of UNIX® system administration experience.
Attending UNIX system administration training courses might be helpful.
|===


=== Solaris Express Developer Edition Installation Guide: Laptop Installations

[cols="1,4"]
|===

| Document Link
| link:./20090715/SOLDEVELINSTALL/html/soldevelinstall.html[Solaris Express Developer Edition Installation Guide: Laptop Installations]

| Topics
| This book provides general guidance for installing the Solaris Express Developer Edition on a laptop computer.

| Target Audience
| This book is intended for anyone interested in installing Solaris Express Developer Edition on laptop hardware.

| Requirements
| To use this book, you should have basic UNIX® system administration experience.
Attending UNIX system administration training courses might be helpful.
|===


=== Solaris Express Installation Guide: Network-Based Installations

[cols="1,4"]
|===

| Document Link
| link:./20090715/SOLINSTALLNET/html/solinstallnet.html[Solaris Express Installation Guide: Network-Based Installations]

| Topics
| This book describes how to install the Solaris™ Operating System (Solaris OS) remotely over a local area network or a wide area network.

This book does not include instructions about how to set up system hardware or other peripherals.

| Target Audience
| This book is intended for system administrators who are responsible for installing the Solaris software.
This book provides advanced Solaris installation information for enterprise system administrators who manage multiple Solaris machines in a networked environment.

| Requirements
| To use this book, you should have 1-2 years of UNIX® system administration experience.
Attending UNIX system administration training courses might be helpful.
|===


=== Solaris Express Installation Guide: Solaris Flash Archives (Creation and Installation)

[cols="1,4"]
|===

| Document Link
| link:./20090715/SOLINSTALLFLASH/html/solinstallflash.html[Solaris Express Installation Guide: Solaris Flash Archives (Creation and Installation)]

| Topics
| This book provides planning information and instructions for creating Solaris™ Flash archives and using Solaris Flash archives to install the Solaris Operating System (OS) on multiple systems.

This book does not include instructions about how to set up system hardware or other peripherals.

| Target Audience
| This book is intended for system administrators who are responsible for installing the Solaris OS.
These procedures are advanced Solaris installation information for enterprise system administrators who manage multiple Solaris machines in a networked environment.

| Requirements
| To use this book, you should have 2 or more years of UNIX® system administration experience.
Attending UNIX system administration training courses might be helpful.
|===

=== Solaris Express Installation Guide: Solaris Live Upgrade and Upgrade Planning

[cols="1,4"]
|===

| Document Link
| link:./20090715/SOLINSTALLUPG/html/solinstallupg.html[Solaris Express Installation Guide: Solaris Live Upgrade and Upgrade Planning]

| Topics
| This book describes how to install and upgrade the Solaris™ Operating System (OS) on both networked and nonnetworked SPARC® and x86 architecture based systems.

This book does not include instructions about how to set up system hardware or other peripherals.

| Target Audience
a| This book is intended for system administrators responsible for installing the Solaris OS.
This book provides both of the following types of information.

- Advanced Solaris installation information for enterprise system administrators who manage multiple Solaris machines in a networked environment
- Basic Solaris installation information for system administrators who perform infrequent Solaris upgrades

| Requirements
| To use this book, you should have 2 or more years of UNIX® system administration experience.
Attending UNIX system administration training courses might be helpful.
|===


=== Solaris Express Installation Guide: Custom JumpStart and Advanced Installations

[cols="1,4"]
|===

| Document Link
| link:./20090715/SOLINSTALLADV/html/solinstalladv.html[Solaris Express Installation Guide: Custom JumpStart and Advanced Installations]

| Topics
| This book describes how to install and upgrade the Solaris™ Operating System (OS) on both networked and nonnetworked SPARC® and x86 architecture based systems.
This book covers using the custom JumpStart installation method and the creation of RAID-1 volumes during installation.

This book does not include instructions about how to set up system hardware or other peripherals.

| Target Audience
a| This book is intended for system administrators responsible for installing the Solaris OS.
This book provides both of the following types of information.

- Advanced Solaris installation information for enterprise system administrators who manage multiple Solaris machines in a networked environment
- Basic Solaris installation information for system administrators who perform infrequent Solaris installations or upgrades

| Requirements
| To use this book, you should have 2 or more years of UNIX® system administration experience.
Attending UNIX system administration training courses might be helpful.
|===


=== Solaris Express Package List

[cols="1,4"]
|===

| Document Link
| link:./20090715/INSTALLPKGLIST/html/installpkglist.html[Solaris Express Package List]

| Topics
| The Solaris Express Package List lists and describes the packages included in the Solaris™ Express Operating System (Solaris OS).
The list includes information about the software groups that contain each package.

| Target Audience
| This book is intended for system administrators responsible for installing the Solaris software.

| Requirements
| To use this book, you should have 1-2 years of UNIX® system administration experience.
Attending UNIX system administration training courses might be helpful.
|===


== Trusted Extensions Systems Administration


=== Solaris Trusted Extensions Installation and Configuration

.Document Link
link:./20090715/TRSOLINSTALL/html/trsolinstall.html[Solaris Trusted Extensions Installation and Configuration]

.Topics

.Target Audience

.Requirements

This book is for knowledgeable system administrators and security administrators who are installing Trusted Extensions software.
The level of trust that is required by your site security policy, and your level of expertise, determines who can perform the configuration tasks.


=== Solaris Trusted Extensions User's Guide

.Document Link
link:./20090715/TRSSUG/html/trssug.html[Solaris Trusted Extensions User's Guide]

.Topics

.Target Audience

.Requirements

This book is for all users of Trusted Extensions.
As a prerequisite, you must be familiar with the Solaris OS and one of the following desktops:

* Common Desktop Environment (CDE)
* The open source GNOME desktop
* Sun Java™ Desktop System

You must also be familiar with the security policy of your organization.


=== Solaris Trusted Extensions Administrator's Procedures

.Document Link
link:./20090715/TRSOLADMPROC/html/trsoladmproc.html[Solaris Trusted Extensions Administrator's Procedures]

.Topics
System installation, configuration, and administration that is specific to Solaris Trusted Extensions

.Target Audience
This book is for knowledgeable system administrators and security administrators who are configuring and administering Trusted Extensions software.
The level of trust that is required by your site security policy, and your level of expertise, determines who can perform the configuration tasks.

.Reguirements
Administrators should be familiar with Solaris administration.
In addition, administrators should understand the following:

* The security features of Trusted Extensions and your site security policy
* Basic concepts and procedures for using a host that is configured with Trusted Extensions, as described in the Solaris Trusted Extensions User’s Guide
* How administrative tasks are divided among roles at your site


=== Solaris Trusted Extensions Label Administration

.Document Link
link:./20090715/TRSOLLBLADMIN/html/trsollbladmin.html[Solaris Trusted Extensions Label Administration]

.Topics

.Target Audience

.Requirements

This book is for security administrators.
Security administrators are responsible for defining the organization's labels.
Some security administrators are also responsible for implementing the labels.
This book is for definers and implementers.


=== Solaris Trusted Extensions Transition Guide

.Document Link
link:./20090715/TRSOLTRANS/html/trsoltrans.html[Solaris Trusted Extensions Transition Guide]

.Topics

.Target Audience

.Requirements

All users should find the book useful.
The Solaris Trusted Extensions Transition Guide is designed for users who are familiar with Trusted Solaris releases and with the Solaris OS.
This book enables these users to more easily use systems that are configured with Solaris Trusted Extensions.


== Development


=== Solaris Dynamic Tracing Guide

.Document Link
link:./20090715/DYNMCTRCGGD/html/dynmctrcggd.html[Solaris Dynamic Tracing Guide]

.Topics

.Target Audience

.Requirements

DTrace is a comprehensive dynamic tracing framework for the Solaris™ Operating System.
DTrace provides a powerful infrastructure to permit administrators, developers, and service personnel to concisely answer arbitrary questions about the behavior of the operating system and user programs.
The Solaris Dynamic Tracing Guide describes how to use DTrace to observe, debug, and tune system behavior.
This book also includes a complete reference for bundled DTrace observability tools and the D programming language.


=== Solaris Modular Debugger Guide

.Document Link
link:./20090715/MODDEBUG/html/moddebug.html[Solaris Modular Debugger Guide]

.Topics

.Target Audience

.Requirements

If you were a detective and were investigating at the scene of a crime, you might interview the witnesses and ask them to describe what happened and who they saw.
However, if there were no witnesses or these descriptions proved insufficient, you might consider collecting fingerprints and forensic evidence that could be examined for DNA to help solve the case.
Often, software program failures divide into analogous categories: problems that can be solved with source-level debugging tools, and problems that require low-level debugging facilities, examination of core files, and knowledge of assembly language to diagnose and correct.
MDB facilitates analysis of this second class of problems.

MDB is most useful when you are programming a complex low-level software system such as an operating system.
The MDB debugging framework allows you to construct your own custom analysis tools to aid in the diagnosis of these low-level problems.
MDB also provides a powerful set of built-in commands that enable you to analyze the state of your program at the assembly language level.


=== Device Driver Tutorial

.Document Link
link:./20090715/DRIVERTUT/html/drivertut.html[Device Driver Tutorial]

.Topics

.Target Audience

.Requirements

You should read this tutorial if you need to develop, install, and configure device drivers for the Solaris OS.
You also should read this book if you need to maintain existing drivers or add new functionality to existing Solaris OS drivers.
Information about the kernel provided in this book also will help you troubleshoot any problems you might encounter installing or configuring Solaris systems.


=== Writing Device Drivers

.Document Link
link:./20090715/DRIVER/html/driver.html[Writing Device Drivers]

.Topics

.Target Audience

.Requirements

This book is written for UNIX® programmers who are familiar with UNIX device drivers.
Overview information is provided, but the book is not intended to serve as a general tutorial on device drivers.


=== Application Packaging Developer's Guide

.Document Link
link:./20090715/PACKINSTALL/html/packinstall.html[Application Packaging Developer's Guide]

.Topics

.Target Audience

.Requirements

This book is intended for application developers whose responsibilities include designing and building packages.

Though much of the book is directed towards novice package developers, it also contains information useful to more experienced package developers.


=== OpenSolaris Distribution Constructor Guide

.Document Link
link:./20090715/DistroConst/html/distroconst.html[OpenSolaris Distribution Constructor Guide]

.Topics

.Target Audience

.Requirements

The distribution constructor is a tool that application developers can use to build their own custom OpenSolaris™ image which they can then distribute to their contacts and customers.


=== Memory and Thread Placement Optimization Developer's Guide

.Document Link
link:./20090715/MTPODG/html/mtpodg.html[Memory and Thread Placement Optimization Developer's Guide]

.Topics

.Target Audience

.Requirements

This book is intended for use by developers who are writing applications in an environment with multiple CPUs and a non-uniform memory architecture.
The programming interfaces and tools that are described in this book give the developer control over the system's behavior and resource allocation.


=== Solaris Containers: Resource Management and Solaris Zones Developer's Guide

.Document Link
link:./20090715/RSCMGRDEVGD/html/rscmgrdevgd.html[Solaris Containers: Resource Management and Solaris Zones Developer's Guide]

.Topics

.Target Audience

.Requirements

This book is for application developers and ISVs who write applications that control or monitor the Solaris Operating System resources.


=== Solaris Trusted Extensions Developer's Guide

.Document Link
link:./20090715/TRSOLDEV/html/trsoldev.html[Solaris Trusted Extensions Developer's Guide]

.Topics

.Target Audience

.Requirements

The Solaris Trusted Extensions Developer's Guide describes how to use the application programming interfaces (APIs) to write new trusted applications for systems that are configured with the Solaris™ Trusted Extensions software.
Readers must be familiar with UNIX® programming and understand security policy concepts.


